# Imagen base oficial de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos necesarios al contenedor
COPY cristiano_stats_app.py .
COPY cristiano_ronaldo.csv .
COPY cr7_bg.jpg .
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto de Streamlit
EXPOSE 8501

# Comando para ejecutar la app
CMD ["streamlit", "run", "cristiano_stats_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
