version: '3.8'

services:
  cristiano_stats_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  # Mapeo del puerto (host:contenedor)
    volumes:
      - .:/app       # Montar el directorio actual en /app (opcional, para desarrollo)
    restart: unless-stopped