name: Deploy FastAPI App on Merge to Develop

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    name: Deploy on local server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop existing container
        run: docker compose down || true

      - name: Build and run new container
        run: docker compose -f streamlit/docker-compose.yml up -d --build

      - name: Notificar a Discord (manual)
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "✅ Deploy completado correctamente desde self-hosted runner"}' \
               ${{ secrets.DISCORD_WEBHOOK }}
