---
name: Deploy FastAPI App on Merge to Develop

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    name: Deploy on local server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop existing container
        run: docker compose down || true

      - name: Build and run new container
        run: docker compose -f streamlit/docker-compose.yml up -d --build

      - name: Notify on Discord
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "🚀 FastAPI deployed on local server after merge to develop"
          avatar: "https://emoji.gg/assets/emoji/1999_rocket.png"
